---
# Role tasks

- name: Create script to handle session timeout
  template:
    src: session_timeout.sh.j2
    dest: "{{ session_timeout_script_path }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
